name: cron refresh
on:
  schedule:
    - cron: '5 0-18 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.PROJ_ID }}
          vercel-org-id: ${{ secrets.ORG_ID }}
